### ISSUE TITLE
WARNING: SCDoc: In Applications/SuperCollider.app/Contents/Resources/HelpSource/Classes/UGen.schelp

### ISSUE THREAD

**Issue by prko** [supercollider-quarks/MathLib#43]
Hello, 

Please see the following topic:
https://github.com/supercollider/supercollider/issues/6129

I could fix it, but I think it should be checked by the author!
Thank you.

**Comment by joslloand** [comment]
Duplicate of https://github.com/supercollider-quarks/MathLib/issues/41

**Comment by dyfer** [comment]
Closing as a duplicate.
